language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - os: osx
      osx_image: xcode11
      language: shell

install:
  - python setup.py install
  - pip install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - py.test --cov=socks5man
after_success:
  - codecov
