language: python
group: travis_latest

python:
- 3.7
- 3.6

matrix:
  fast_finish: true
  include:
  - os: linux
    name: PEP8 MyPy Coverage
    python: 3.7
    install: pip install -e .
    after_success:
    - coveralls
  - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36
  - os: windows
    language: minimal
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    yes | sudo port install python$PYTHON;
    yes | sudo port install py$PYTHON-pip;
    sudo port select --set python3 python$PYTHON;
    sudo port select --set pip pip$PYTHON;
    pip install pyinstaller --user;
    export PATH=$PATH:/Users/travis/Library/Python/$PYTHON/bin;
    fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    python3 --version;
    pip --version;
    pyinstaller --version;
    fi

install:
  - pip install -e .
  - pip install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - pytest
after_success:
  - codecov
