matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov

install:
  - python setup.py install
  - pip install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - py.test --cov=socks5man
after_success:
  - codecov
