language: python

matrix:
  fast_finish: true
  include:
    - python: 2.7
    - os: osx
      osx_image: xcode9.3beta
      language: generic

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        brew update || brew update
        wget https://bootstrap.pypa.io/get-pip.py
        sudo python get-pip.py
        sudo pip install virtualenv
        virtualenv $HOME
        source $HOME/bin/activate
    fi
install:
  - python setup.py install
  - pip install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - py.test --cov=socks5man
after_success:
  - codecov
