language: python
group: travis_latest

python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    python: 3.7
  - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install codecov
      script: python3 -m pytest
      after_success: python 3 -m codecov
  - os: windows
    language: minimal
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install:
  - pip3 install -e .
  - pip3 install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - py.test --cov=socks5man
after_success:
  - codecov
