language: python
group: travis_latest

python:
- 3.7
- 3.6

matrix:
  include:
  - os: linux
    python: 3.7
  - os: osx
    language: minimal
  - os: windows
    language: minimal
    before_install:
    - choco install python3
    - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install:
  - pip install -e .
  - pip install pytest>=3.6 mock "pytest-cov<2.6.0" codecov
script:
  - py.test --cov=socks5man
after_success:
  - codecov
