environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: 3.6

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: 3.7

install:
  - "python.exe setup.py install"
  - "pip.exe install -e ."
  - "pip.exe install pytest mock pytest-cov codecov"

build: off

test_script:
  - "pytest.exe --cov=socks5man"

after_test:
  - "codecov.exe"
