environment:
  matrix:
    - PYTHON: "C:\Python37-x64"

install:
  - "python.exe setup.py install"
  - "pip.exe install -e ."
  - "pip.exe install pytest mock pytest-cov codecov"

build: off

test_script:
  - "pytest.exe --cov=socks5man"

after_test:
  - "codecov.exe"
